### ISSUE TITLE
Melodic: Decimal values are not correctly parsed

### ISSUE THREAD

**Issue by VictorLamoine** [ros/urdf#22]
A URDF value that is lower than 1.0 will be interpreted as zero.

This leads to:
- RViz meshes showing black: https://github.com/ros-visualization/rviz/issues/1298
- Small geometries not displaying at all in RViz: https://github.com/ros-visualization/rviz/issues/1299

**Comment by VictorLamoine** [comment]
I can't find any commit that could be the source of this problem; I'm unable to track where it comes from.
If something has an idea or knows, please ping me here!

**Comment by clalancette** [comment]
This is likely a duplicate of https://github.com/ros-visualization/rviz/issues/1249, https://github.com/ros-visualization/rviz/issues/1151, fixed by https://github.com/ros/urdfdom_headers/pull/42.  We are trying to get that released into bionic in https://github.com/ros/urdfdom_headers/issues/45.  @VictorLamoine , can you confirm that the workaround in https://github.com/ros-visualization/rviz/issues/1249#issuecomment-403351217 fixes the problem for you?

**Comment by gavanderhoorn** [comment]
https://github.com/ros-visualization/rviz/issues/1298 is probably also caused by ros/urdfdom_headers#42.

**Comment by VictorLamoine** [comment]
I confirm the workaround fixes the issue, I will close this one as this is a duplicate, sorry.

**Comment by clalancette** [comment]
@VictorLamoine thanks for confirming.
