### ISSUE TITLE
urdf of a parallel robot

### ISSUE THREAD

**Issue by ghost** [ros/urdf#23]
Hello

I need to make a conversion from solidworks to collada(.dae) file. The process is to make a urdf file from the solidworks model and then using collada_urdf convertor of ROS I can do the conversion. But unfortunately, urdf files ddon't support parallel mechanisms. I wanted to know is there any other way for making a urdf file from a parallel mechanism?

Thank You

**Comment by clalancette** [comment]
In general, questions like this are better asked on https://answers.ros.org; there is a wider community watching there which may be able to answer your question, and the answer will be archived for the future.  Because of that, I'm going to close this out and encourage you to ask the question there.  Thanks.
